spring:
  profiles:
    active: composite
  cloud:
    config:
      discovery:
        enabled: true
      server:
        composite:
          - type: native
            search-locations: classpath:config
        bootstrap: true

server:
  port: 8888
