spring:
  application:
    name: config

    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
        registerWithEureka: true
        fetchRegistry: true
        enabled: true

