spring:
   application:
     name : zuul
   eureka:
     client:
       serviceUrl:
         defaultZone: http://localhost:8761/eureka
       registerWithEureka: true
       fetchRegistry: true
       enabled: true

server:
  port : 8765